# Generated by Django 4.2.11 on 2024-04-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='checkbox',
            field=models.BooleanField(default=False),
        ),
    ]
